name: My First GitHub Action

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: Hello World

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      - name: Print My Variable
        run: echo $MY_VARIABLE
