name: My First GitHub Action

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: This is a variable

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      - name: Afficher la valeur du secret
        run: echo "La valeur du secret est :" "abc" ${{secrets.MY_SECRET}}
      - name: Print My Variable
        run: echo "${{env.MY_VARIABLE}}"
